import type { ThemeConfig } from '@/types/ec9v3';

export const THEMES: ThemeConfig[] = [
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    category: 'Cyberpunk',
    colors: {
      background: '#0a0a12',
      foreground: '#e0e4f0',
      primary: '#00d4ff',
      primaryForeground: '#0a0a12',
      secondary: '#1a1a2e',
      secondaryForeground: '#e0e4f0',
      muted: '#1a1a2e',
      mutedForeground: '#505878',
      accent: '#ff0080',
      accentForeground: '#ffffff',
      border: '#2a2a3e',
      card: '#0f0f1a',
      cardForeground: '#e0e4f0',
      input: '#1a1a2e',
      ring: '#00d4ff',
      destructive: '#ff4060',
      popover: '#0f0f1a',
      popoverForeground: '#e0e4f0',
      sidebar: '#080810',
      sidebarForeground: '#e0e4f0',
      sidebarPrimary: '#00d4ff',
      sidebarPrimaryForeground: '#0a0a12',
      sidebarAccent: '#1a1a2e',
      sidebarAccentForeground: '#e0e4f0',
      sidebarBorder: '#2a2a3e',
      sidebarRing: '#00d4ff',
    },
  },
  {
    id: 'cyberpunk-purple',
    name: 'Neon Purple',
    category: 'Cyberpunk',
    colors: {
      background: '#0d0515',
      foreground: '#e8dff5',
      primary: '#bf5af2',
      primaryForeground: '#0d0515',
      secondary: '#1a0f2e',
      secondaryForeground: '#e8dff5',
      muted: '#1a0f2e',
      mutedForeground: '#6e5b8a',
      accent: '#00ff88',
      accentForeground: '#0d0515',
      border: '#2e1f4e',
      card: '#110820',
      cardForeground: '#e8dff5',
      input: '#1a0f2e',
      ring: '#bf5af2',
      destructive: '#ff453a',
      popover: '#110820',
      popoverForeground: '#e8dff5',
      sidebar: '#090310',
      sidebarForeground: '#e8dff5',
      sidebarPrimary: '#bf5af2',
      sidebarPrimaryForeground: '#0d0515',
      sidebarAccent: '#1a0f2e',
      sidebarAccentForeground: '#e8dff5',
      sidebarBorder: '#2e1f4e',
      sidebarRing: '#bf5af2',
    },
  },
  {
    id: 'cyberpunk-green',
    name: 'Matrix Green',
    category: 'Cyberpunk',
    colors: {
      background: '#050a05',
      foreground: '#c0f0c0',
      primary: '#00ff41',
      primaryForeground: '#050a05',
      secondary: '#0a150a',
      secondaryForeground: '#c0f0c0',
      muted: '#0a150a',
      mutedForeground: '#4a7a4a',
      accent: '#00d4ff',
      accentForeground: '#050a05',
      border: '#153015',
      card: '#081008',
      cardForeground: '#c0f0c0',
      input: '#0a150a',
      ring: '#00ff41',
      destructive: '#ff4040',
      popover: '#081008',
      popoverForeground: '#c0f0c0',
      sidebar: '#030803',
      sidebarForeground: '#c0f0c0',
      sidebarPrimary: '#00ff41',
      sidebarPrimaryForeground: '#050a05',
      sidebarAccent: '#0a150a',
      sidebarAccentForeground: '#c0f0c0',
      sidebarBorder: '#153015',
      sidebarRing: '#00ff41',
    },
  },
  {
    id: 'dark-default',
    name: 'Dark Default',
    category: 'Dark',
    colors: {
      background: '#09090b',
      foreground: '#fafafa',
      primary: '#fafafa',
      primaryForeground: '#18181b',
      secondary: '#27272a',
      secondaryForeground: '#fafafa',
      muted: '#27272a',
      mutedForeground: '#a1a1aa',
      accent: '#27272a',
      accentForeground: '#fafafa',
      border: '#27272a',
      card: '#0a0a0c',
      cardForeground: '#fafafa',
      input: '#27272a',
      ring: '#d4d4d8',
      destructive: '#ef4444',
      popover: '#09090b',
      popoverForeground: '#fafafa',
      sidebar: '#08080a',
      sidebarForeground: '#fafafa',
      sidebarPrimary: '#fafafa',
      sidebarPrimaryForeground: '#18181b',
      sidebarAccent: '#27272a',
      sidebarAccentForeground: '#fafafa',
      sidebarBorder: '#27272a',
      sidebarRing: '#d4d4d8',
    },
  },
  {
    id: 'dark-zinc',
    name: 'Zinc Dark',
    category: 'Dark',
    colors: {
      background: '#09090b',
      foreground: '#fafafa',
      primary: '#a1a1aa',
      primaryForeground: '#09090b',
      secondary: '#18181b',
      secondaryForeground: '#fafafa',
      muted: '#18181b',
      mutedForeground: '#a1a1aa',
      accent: '#27272a',
      accentForeground: '#fafafa',
      border: '#27272a',
      card: '#0c0c0e',
      cardForeground: '#fafafa',
      input: '#27272a',
      ring: '#71717a',
      destructive: '#dc2626',
      popover: '#09090b',
      popoverForeground: '#fafafa',
      sidebar: '#0a0a0c',
      sidebarForeground: '#fafafa',
      sidebarPrimary: '#a1a1aa',
      sidebarPrimaryForeground: '#09090b',
      sidebarAccent: '#18181b',
      sidebarAccentForeground: '#fafafa',
      sidebarBorder: '#27272a',
      sidebarRing: '#71717a',
    },
  },
  {
    id: 'dark-slate',
    name: 'Slate Dark',
    category: 'Dark',
    colors: {
      background: '#0f172a',
      foreground: '#f8fafc',
      primary: '#38bdf8',
      primaryForeground: '#0f172a',
      secondary: '#1e293b',
      secondaryForeground: '#f8fafc',
      muted: '#1e293b',
      mutedForeground: '#94a3b8',
      accent: '#1e293b',
      accentForeground: '#f8fafc',
      border: '#334155',
      card: '#0c1424',
      cardForeground: '#f8fafc',
      input: '#1e293b',
      ring: '#38bdf8',
      destructive: '#f87171',
      popover: '#0f172a',
      popoverForeground: '#f8fafc',
      sidebar: '#0b1222',
      sidebarForeground: '#f8fafc',
      sidebarPrimary: '#38bdf8',
      sidebarPrimaryForeground: '#0f172a',
      sidebarAccent: '#1e293b',
      sidebarAccentForeground: '#f8fafc',
      sidebarBorder: '#334155',
      sidebarRing: '#38bdf8',
    },
  },
  {
    id: 'dark-rose',
    name: 'Rose Dark',
    category: 'Dark',
    colors: {
      background: '#0f0a0c',
      foreground: '#fde7e7',
      primary: '#fb7185',
      primaryForeground: '#0f0a0c',
      secondary: '#1f1018',
      secondaryForeground: '#fde7e7',
      muted: '#1f1018',
      mutedForeground: '#9a7a80',
      accent: '#f43f5e',
      accentForeground: '#ffffff',
      border: '#3a1f2a',
      card: '#120c0e',
      cardForeground: '#fde7e7',
      input: '#1f1018',
      ring: '#fb7185',
      destructive: '#ef4444',
      popover: '#120c0e',
      popoverForeground: '#fde7e7',
      sidebar: '#0c080a',
      sidebarForeground: '#fde7e7',
      sidebarPrimary: '#fb7185',
      sidebarPrimaryForeground: '#0f0a0c',
      sidebarAccent: '#1f1018',
      sidebarAccentForeground: '#fde7e7',
      sidebarBorder: '#3a1f2a',
      sidebarRing: '#fb7185',
    },
  },
  {
    id: 'dark-amber',
    name: 'Amber Dark',
    category: 'Dark',
    colors: {
      background: '#0f0d08',
      foreground: '#fef3c7',
      primary: '#fbbf24',
      primaryForeground: '#0f0d08',
      secondary: '#1f1a10',
      secondaryForeground: '#fef3c7',
      muted: '#1f1a10',
      mutedForeground: '#9a8a60',
      accent: '#f59e0b',
      accentForeground: '#0f0d08',
      border: '#3a3018',
      card: '#120f0a',
      cardForeground: '#fef3c7',
      input: '#1f1a10',
      ring: '#fbbf24',
      destructive: '#ef4444',
      popover: '#120f0a',
      popoverForeground: '#fef3c7',
      sidebar: '#0c0a06',
      sidebarForeground: '#fef3c7',
      sidebarPrimary: '#fbbf24',
      sidebarPrimaryForeground: '#0f0d08',
      sidebarAccent: '#1f1a10',
      sidebarAccentForeground: '#fef3c7',
      sidebarBorder: '#3a3018',
      sidebarRing: '#fbbf24',
    },
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'Midnight',
    colors: {
      background: '#020818',
      foreground: '#d0daf0',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      secondary: '#0c1832',
      secondaryForeground: '#d0daf0',
      muted: '#0c1832',
      mutedForeground: '#5068a0',
      accent: '#6366f1',
      accentForeground: '#ffffff',
      border: '#1a2e5a',
      card: '#040e22',
      cardForeground: '#d0daf0',
      input: '#0c1832',
      ring: '#3b82f6',
      destructive: '#ef4444',
      popover: '#040e22',
      popoverForeground: '#d0daf0',
      sidebar: '#010610',
      sidebarForeground: '#d0daf0',
      sidebarPrimary: '#3b82f6',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#0c1832',
      sidebarAccentForeground: '#d0daf0',
      sidebarBorder: '#1a2e5a',
      sidebarRing: '#3b82f6',
    },
  },
  {
    id: 'midnight-indigo',
    name: 'Deep Indigo',
    category: 'Midnight',
    colors: {
      background: '#08061a',
      foreground: '#d8d0f0',
      primary: '#818cf8',
      primaryForeground: '#08061a',
      secondary: '#120f2e',
      secondaryForeground: '#d8d0f0',
      muted: '#120f2e',
      mutedForeground: '#6a60a0',
      accent: '#a78bfa',
      accentForeground: '#08061a',
      border: '#251e52',
      card: '#0a0820',
      cardForeground: '#d8d0f0',
      input: '#120f2e',
      ring: '#818cf8',
      destructive: '#f87171',
      popover: '#0a0820',
      popoverForeground: '#d8d0f0',
      sidebar: '#060412',
      sidebarForeground: '#d8d0f0',
      sidebarPrimary: '#818cf8',
      sidebarPrimaryForeground: '#08061a',
      sidebarAccent: '#120f2e',
      sidebarAccentForeground: '#d8d0f0',
      sidebarBorder: '#251e52',
      sidebarRing: '#818cf8',
    },
  },
  {
    id: 'ocean-teal',
    name: 'Ocean Teal',
    category: 'Ocean',
    colors: {
      background: '#021a1a',
      foreground: '#d0f0f0',
      primary: '#14b8a6',
      primaryForeground: '#021a1a',
      secondary: '#0a2e2e',
      secondaryForeground: '#d0f0f0',
      muted: '#0a2e2e',
      mutedForeground: '#508888',
      accent: '#06b6d4',
      accentForeground: '#021a1a',
      border: '#165050',
      card: '#041e1e',
      cardForeground: '#d0f0f0',
      input: '#0a2e2e',
      ring: '#14b8a6',
      destructive: '#f87171',
      popover: '#041e1e',
      popoverForeground: '#d0f0f0',
      sidebar: '#011212',
      sidebarForeground: '#d0f0f0',
      sidebarPrimary: '#14b8a6',
      sidebarPrimaryForeground: '#021a1a',
      sidebarAccent: '#0a2e2e',
      sidebarAccentForeground: '#d0f0f0',
      sidebarBorder: '#165050',
      sidebarRing: '#14b8a6',
    },
  },
  {
    id: 'ocean-cyan',
    name: 'Deep Cyan',
    category: 'Ocean',
    colors: {
      background: '#021218',
      foreground: '#d0e8f8',
      primary: '#06b6d4',
      primaryForeground: '#021218',
      secondary: '#0a2030',
      secondaryForeground: '#d0e8f8',
      muted: '#0a2030',
      mutedForeground: '#507898',
      accent: '#22d3ee',
      accentForeground: '#021218',
      border: '#164060',
      card: '#041820',
      cardForeground: '#d0e8f8',
      input: '#0a2030',
      ring: '#06b6d4',
      destructive: '#f87171',
      popover: '#041820',
      popoverForeground: '#d0e8f8',
      sidebar: '#010e12',
      sidebarForeground: '#d0e8f8',
      sidebarPrimary: '#06b6d4',
      sidebarPrimaryForeground: '#021218',
      sidebarAccent: '#0a2030',
      sidebarAccentForeground: '#d0e8f8',
      sidebarBorder: '#164060',
      sidebarRing: '#06b6d4',
    },
  },
  {
    id: 'forest-emerald',
    name: 'Forest Emerald',
    category: 'Forest',
    colors: {
      background: '#031208',
      foreground: '#d0f0d8',
      primary: '#10b981',
      primaryForeground: '#031208',
      secondary: '#0a2e18',
      secondaryForeground: '#d0f0d8',
      muted: '#0a2e18',
      mutedForeground: '#508868',
      accent: '#34d399',
      accentForeground: '#031208',
      border: '#185030',
      card: '#041a0c',
      cardForeground: '#d0f0d8',
      input: '#0a2e18',
      ring: '#10b981',
      destructive: '#f87171',
      popover: '#041a0c',
      popoverForeground: '#d0f0d8',
      sidebar: '#020e06',
      sidebarForeground: '#d0f0d8',
      sidebarPrimary: '#10b981',
      sidebarPrimaryForeground: '#031208',
      sidebarAccent: '#0a2e18',
      sidebarAccentForeground: '#d0f0d8',
      sidebarBorder: '#185030',
      sidebarRing: '#10b981',
    },
  },
  {
    id: 'warm-orange',
    name: 'Warm Orange',
    category: 'Warm',
    colors: {
      background: '#120c04',
      foreground: '#fde8d0',
      primary: '#f97316',
      primaryForeground: '#120c04',
      secondary: '#2e1a0a',
      secondaryForeground: '#fde8d0',
      muted: '#2e1a0a',
      mutedForeground: '#a07850',
      accent: '#fb923c',
      accentForeground: '#120c04',
      border: '#503018',
      card: '#180f08',
      cardForeground: '#fde8d0',
      input: '#2e1a0a',
      ring: '#f97316',
      destructive: '#ef4444',
      popover: '#180f08',
      popoverForeground: '#fde8d0',
      sidebar: '#0e0804',
      sidebarForeground: '#fde8d0',
      sidebarPrimary: '#f97316',
      sidebarPrimaryForeground: '#120c04',
      sidebarAccent: '#2e1a0a',
      sidebarAccentForeground: '#fde8d0',
      sidebarBorder: '#503018',
      sidebarRing: '#f97316',
    },
  },
  {
    id: 'warm-red',
    name: 'Ember Red',
    category: 'Warm',
    colors: {
      background: '#120408',
      foreground: '#fde0e8',
      primary: '#ef4444',
      primaryForeground: '#ffffff',
      secondary: '#2e0a14',
      secondaryForeground: '#fde0e8',
      muted: '#2e0a14',
      mutedForeground: '#a05068',
      accent: '#f87171',
      accentForeground: '#120408',
      border: '#501828',
      card: '#18060c',
      cardForeground: '#fde0e8',
      input: '#2e0a14',
      ring: '#ef4444',
      destructive: '#ef4444',
      popover: '#18060c',
      popoverForeground: '#fde0e8',
      sidebar: '#0e0306',
      sidebarForeground: '#fde0e8',
      sidebarPrimary: '#ef4444',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#2e0a14',
      sidebarAccentForeground: '#fde0e8',
      sidebarBorder: '#501828',
      sidebarRing: '#ef4444',
    },
  },
  {
    id: 'light-clean',
    name: 'Clean Light',
    category: 'Light',
    colors: {
      background: '#ffffff',
      foreground: '#18181b',
      primary: '#18181b',
      primaryForeground: '#fafafa',
      secondary: '#f4f4f5',
      secondaryForeground: '#18181b',
      muted: '#f4f4f5',
      mutedForeground: '#a1a1aa',
      accent: '#f4f4f5',
      accentForeground: '#18181b',
      border: '#e4e4e7',
      card: '#ffffff',
      cardForeground: '#18181b',
      input: '#e4e4e7',
      ring: '#18181b',
      destructive: '#ef4444',
      popover: '#ffffff',
      popoverForeground: '#18181b',
      sidebar: '#f8f8f8',
      sidebarForeground: '#18181b',
      sidebarPrimary: '#18181b',
      sidebarPrimaryForeground: '#fafafa',
      sidebarAccent: '#f4f4f5',
      sidebarAccentForeground: '#18181b',
      sidebarBorder: '#e4e4e7',
      sidebarRing: '#18181b',
    },
  },
  {
    id: 'light-blue',
    name: 'Sky Light',
    category: 'Light',
    colors: {
      background: '#f8faff',
      foreground: '#1e293b',
      primary: '#2563eb',
      primaryForeground: '#ffffff',
      secondary: '#e8f0fe',
      secondaryForeground: '#1e293b',
      muted: '#e8f0fe',
      mutedForeground: '#64748b',
      accent: '#dbeafe',
      accentForeground: '#1e3a5f',
      border: '#cbd5e1',
      card: '#ffffff',
      cardForeground: '#1e293b',
      input: '#cbd5e1',
      ring: '#2563eb',
      destructive: '#ef4444',
      popover: '#ffffff',
      popoverForeground: '#1e293b',
      sidebar: '#f0f5ff',
      sidebarForeground: '#1e293b',
      sidebarPrimary: '#2563eb',
      sidebarPrimaryForeground: '#ffffff',
      sidebarAccent: '#e8f0fe',
      sidebarAccentForeground: '#1e293b',
      sidebarBorder: '#cbd5e1',
      sidebarRing: '#2563eb',
    },
  },
];

export function applyTheme(themeId: string): void {
  if (typeof document === 'undefined') return;

  const theme = THEMES.find((t) => t.id === themeId);
  if (!theme) return;

  const root = document.documentElement;
  const c = theme.colors;

  root.style.setProperty('--background', c.background);
  root.style.setProperty('--foreground', c.foreground);
  root.style.setProperty('--card', c.card);
  root.style.setProperty('--card-foreground', c.cardForeground);
  root.style.setProperty('--popover', c.popover);
  root.style.setProperty('--popover-foreground', c.popoverForeground);
  root.style.setProperty('--primary', c.primary);
  root.style.setProperty('--primary-foreground', c.primaryForeground);
  root.style.setProperty('--secondary', c.secondary);
  root.style.setProperty('--secondary-foreground', c.secondaryForeground);
  root.style.setProperty('--muted', c.muted);
  root.style.setProperty('--muted-foreground', c.mutedForeground);
  root.style.setProperty('--accent', c.accent);
  root.style.setProperty('--accent-foreground', c.accentForeground);
  root.style.setProperty('--destructive', c.destructive);
  root.style.setProperty('--border', c.border);
  root.style.setProperty('--input', c.input);
  root.style.setProperty('--ring', c.ring);
  root.style.setProperty('--sidebar', c.sidebar);
  root.style.setProperty('--sidebar-foreground', c.sidebarForeground);
  root.style.setProperty('--sidebar-primary', c.sidebarPrimary);
  root.style.setProperty('--sidebar-primary-foreground', c.sidebarPrimaryForeground);
  root.style.setProperty('--sidebar-accent', c.sidebarAccent);
  root.style.setProperty('--sidebar-accent-foreground', c.sidebarAccentForeground);
  root.style.setProperty('--sidebar-border', c.sidebarBorder);
  root.style.setProperty('--sidebar-ring', c.sidebarRing);

  const isLight = theme.category === 'Light';
  if (isLight) {
    root.classList.remove('dark');
  } else {
    root.classList.add('dark');
  }
}
